### ISSUE TITLE
Need to finish Docker integration

### ISSUE THREAD

**Issue by bsommardahl** [AcklenAvenue/glee#7]
I started to build some docker artifacts, but I was learning as I went. When I left them, the dockerfile and compose config were working, but I'm not convinced I was doing it right. I believe, if we're using docker, we should be "forced" in a way to use docker while running and testing glee locally. As it is right now, devs have a choice. If Docker is going to be a sustainable solution, it needs to be the only choice (I think). This needs some more research and possibly pairing with a mentor.

**Comment by bsommardahl** [comment]
I should not be able to run `npm run start` and the application successfully start without docker.

**Comment by dantedubon** [comment]
This is still a thing to address?
